export const TECHFIND_INTAKE_STEPS = {
  AWAITING_MENU: 'AWAITING_MENU',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_BUSINESS: 'AWAITING_BUSINESS',
  AWAITING_QUALIFICATION: 'AWAITING_QUALIFICATION',
  AWAITING_PLAAGG_INDUSTRY: 'AWAITING_PLAAGG_INDUSTRY',
  AWAITING_PLAAGG_OTHER: 'AWAITING_PLAAGG_OTHER',
  AWAITING_PLAAGG_DEMO: 'AWAITING_PLAAGG_DEMO',
  AWAITING_PLAAGG_FINISH: 'AWAITING_PLAAGG_FINISH',
  COMPLETE: 'COMPLETE',
} as const;

export type TechfindIntakeStep =
  (typeof TECHFIND_INTAKE_STEPS)[keyof typeof TECHFIND_INTAKE_STEPS];
