export const TECHFIND_INTAKE_STEPS = {
  AWAITING_MENU: 'AWAITING_MENU',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_BUSINESS: 'AWAITING_BUSINESS',
  AWAITING_QUALIFICATION: 'AWAITING_QUALIFICATION',
  COMPLETE: 'COMPLETE',
} as const;

export type TechfindIntakeStep =
  (typeof TECHFIND_INTAKE_STEPS)[keyof typeof TECHFIND_INTAKE_STEPS];
