export const POS_OPS_STEPS = {
  MENU: 'MENU',
  SALE_SEARCH: 'SALE_SEARCH',
  SALE_PICK: 'SALE_PICK',
  SALE_QTY: 'SALE_QTY',
  SALE_MORE: 'SALE_MORE',
  SALE_PAYMENT: 'SALE_PAYMENT',
  SALE_CREDIT_SEARCH: 'SALE_CREDIT_SEARCH',
  SALE_CREDIT_PICK: 'SALE_CREDIT_PICK',
  SALE_CONFIRM: 'SALE_CONFIRM',
  CREDIT_SEARCH: 'CREDIT_SEARCH',
  CREDIT_PICK: 'CREDIT_PICK',
  PAY_SEARCH: 'PAY_SEARCH',
  PAY_PICK: 'PAY_PICK',
  PAY_AMOUNT: 'PAY_AMOUNT',
  PAY_METHOD: 'PAY_METHOD',
  PAY_CONFIRM: 'PAY_CONFIRM',
  // Quick-sale fast path
  QUICK_PRODUCT_PICK: 'QUICK_PRODUCT_PICK',
  QUICK_CUSTOMER_PICK: 'QUICK_CUSTOMER_PICK',
  QUICK_PAYMENT: 'QUICK_PAYMENT',
  QUICK_CONFIRM: 'QUICK_CONFIRM',
  DONE: 'DONE',
} as const;

export type PosOpsStep = (typeof POS_OPS_STEPS)[keyof typeof POS_OPS_STEPS];
