export const ENQUIRY_STEPS = {
  AWAITING_EVENT_TYPE: 'AWAITING_EVENT_TYPE',
  AWAITING_DATE: 'AWAITING_DATE',
  AWAITING_SERVICES: 'AWAITING_SERVICES',
  AWAITING_GUESTS: 'AWAITING_GUESTS',
  AWAITING_VENUE: 'AWAITING_VENUE',
  AWAITING_INTENT: 'AWAITING_INTENT',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_PHONE: 'AWAITING_PHONE',
  AWAITING_CONFIRM: 'AWAITING_CONFIRM',
  SUBMITTED: 'SUBMITTED',
} as const;

export type EnquiryStep = (typeof ENQUIRY_STEPS)[keyof typeof ENQUIRY_STEPS];
