export const ENQUIRY_STEPS = {
  AWAITING_RETURNING_CHOICE: 'AWAITING_RETURNING_CHOICE',
  AWAITING_EVENT_TYPE: 'AWAITING_EVENT_TYPE',
  AWAITING_DATE: 'AWAITING_DATE',
  AWAITING_SERVICES: 'AWAITING_SERVICES',
  AWAITING_GUESTS: 'AWAITING_GUESTS',
  AWAITING_VENUE: 'AWAITING_VENUE',
  AWAITING_BUDGET: 'AWAITING_BUDGET',
  AWAITING_DETAILS: 'AWAITING_DETAILS',
  AWAITING_NAME: 'AWAITING_NAME',
  AWAITING_PHONE: 'AWAITING_PHONE',
  AWAITING_HANDOVER_NAME: 'AWAITING_HANDOVER_NAME',
  AWAITING_CONFIRM: 'AWAITING_CONFIRM',
  SUBMITTED: 'SUBMITTED',
} as const;

export type EnquiryStep = (typeof ENQUIRY_STEPS)[keyof typeof ENQUIRY_STEPS];
